# Generated by Django 5.0.1 on 2024-02-17 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_name', models.CharField(default='Default Name', max_length=255)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=255)),
            ],
            options={
                'permissions': [('can_add_product', 'Can add product'), ('can_update_product', 'Can update product'), ('can_delete_product', 'Can delete product')],
            },
        ),
    ]
