# Generated by Django 5.0.1 on 2024-02-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
