# Generated by Django 5.0.1 on 2024-03-09 10:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('province', models.CharField(choices=[('Province 1', 'Koshi Province'), ('Province 2', 'Madesh Province'), ('Province 3', 'Bagmati Province'), ('Province 4', 'Gandaki Province'), ('Province 5', 'Lumbini Province'), ('Province 6', 'Karnali Province'), ('Province 7', 'Sudurpashchim Province')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('tole', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(limit_choices_to={'groups__name': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
