# Generated by Django 5.0.1 on 2024-02-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_discount_pecentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='discount_pecentage',
            new_name='discount_percentage',
        ),
    ]
